language: c

compiler:
  - clang
  - gcc

os:
  - freebsd
  - linux
  - osx

arch:
  - amd64
  - s390x

before_script:
  if [[ ${TRAVIS_CPU_ARCH} == 's390x' ]]; then
      sudo apt-get update && sudo apt-get install -y libncursesw5-dev ;
  fi

script:
  - ./autogen.sh
  # clang might warn about C11 generic selections in isnan()
  - CFLAGS=-Wno-c11-extensions ./configure --enable-werror
  - make -k
  - CFLAGS=-Wno-c11-extensions make distcheck DISTCHECK_CONFIGURE_FLAGS=--enable-werror
