language: c

compiler:
  - clang
  - gcc

os:
  - freebsd

script:
  - ./autogen.sh
  - ./configure --enable-werror
  - make -k
  - make distcheck DISTCHECK_CONFIGURE_FLAGS=--enable-werror
  - sudo make install
  - make installcheck
