/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Affinity
#define HEADER_Affinity
/*
htop - Affinity.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/


typedef struct Affinity_ {
   int size;
   int used;
   int* cpus;
} Affinity;


Affinity* Affinity_new();

void Affinity_delete(Affinity* this);

void Affinity_add(Affinity* this, int id);


#endif
