/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_AffinityPanel
#define HEADER_AffinityPanel

#include "ProcessList.h"
#include "Panel.h"
#include "CheckItem.h"

#include "debug.h"
#include <assert.h>

Panel* AffinityPanel_new(ProcessList* pl, Affinity* affinity);

Affinity* AffinityPanel_getAffinity(Panel* this);

#endif
