/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_AvailableColumnsPanel
#define HEADER_AvailableColumnsPanel

#include "Settings.h"
#include "Header.h"
#include "ScreenManager.h"
#include "ColumnsPanel.h"

#include "Panel.h"

#include "debug.h"
#include <assert.h>


typedef struct AvailableColumnsPanel_ {
   Panel super;
   Panel* columns;

   Settings* settings;
   ScreenManager* scr;
} AvailableColumnsPanel;


AvailableColumnsPanel* AvailableColumnsPanel_new(Settings* settings, Panel* columns, ScreenManager* scr);

#endif
