/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_AvailableMetersListBox
#define HEADER_AvailableMetersListBox

#include "Settings.h"
#include "Header.h"
#include "ScreenManager.h"

#include "ListBox.h"

#include "debug.h"
#include <assert.h>


typedef struct AvailableMetersListBox_ {
   ListBox super;

   Settings* settings;
   ListBox* leftBox;
   ListBox* rightBox;
   ScreenManager* scr;
} AvailableMetersListBox;


AvailableMetersListBox* AvailableMetersListBox_new(Settings* settings, ListBox* leftMeters, ListBox* rightMeters, ScreenManager* scr);

void AvailableMetersListBox_delete(Object* object);


HandlerResult AvailableMetersListBox_EventHandler(ListBox* super, int ch);

#endif
