/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_AvailableColumnsPanel
#define HEADER_AvailableColumnsPanel

#include "Settings.h"
#include "Header.h"
#include "ScreenManager.h"

#include "Panel.h"

#include "debug.h"
#include <assert.h>


typedef struct AvailableColumnsPanel_ {
   Panel super;

   Settings* settings;
   ScreenManager* scr;
   Panel* columns;
} AvailableColumnsPanel;


AvailableColumnsPanel* AvailableColumnsPanel_new(Settings* settings, Panel* columns, ScreenManager* scr);

void AvailableColumnsPanel_delete(Object* object);

HandlerResult AvailableColumnsPanel_eventHandler(Panel* super, int ch);

#endif
