/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_AvailableMetersPanel
#define HEADER_AvailableMetersPanel

#include "Settings.h"
#include "Header.h"
#include "ScreenManager.h"

#include "Panel.h"

#include "debug.h"
#include <assert.h>


typedef struct AvailableMetersPanel_ {
   Panel super;

   Settings* settings;
   Panel* leftBox;
   Panel* rightBox;
   ScreenManager* scr;
} AvailableMetersPanel;


AvailableMetersPanel* AvailableMetersPanel_new(Settings* settings, Panel* leftMeters, Panel* rightMeters, ScreenManager* scr);

void AvailableMetersPanel_delete(Object* object);


HandlerResult AvailableMetersPanel_EventHandler(Panel* super, int ch);

#endif
