/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CategoriesPanel
#define HEADER_CategoriesPanel

#include "AvailableMetersPanel.h"
#include "MetersPanel.h"
#include "DisplayOptionsPanel.h"
#include "ColumnsPanel.h"
#include "ColorsPanel.h"
#include "AvailableColumnsPanel.h"

#include "Panel.h"

#include "debug.h"
#include <assert.h>


typedef struct CategoriesPanel_ {
   Panel super;

   Settings* settings;
   ScreenManager* scr;
} CategoriesPanel;


void CategoriesPanel_makeMetersPage(CategoriesPanel* this);

CategoriesPanel* CategoriesPanel_new(Settings* settings, ScreenManager* scr);

#endif
