/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ClockMeter
#define HEADER_ClockMeter
/*
htop - ClockMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int ClockMeter_attributes[];

extern MeterType ClockMeter;

#endif
