/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_ColorsListBox
#define HEADER_ColorsListBox


#include "ListBox.h"
#include "CheckItem.h"
#include "Settings.h"
#include "ScreenManager.h"

#include "debug.h"
#include <assert.h>


typedef struct ColorsListBox_ {
   ListBox super;

   Settings* settings;
   ScreenManager* scr;
   bool check[5];
} ColorsListBox;


ColorsListBox* ColorsListBox_new(Settings* settings, ScreenManager* scr);

void ColorsListBox_delete(Object* object);

HandlerResult ColorsListBox_EventHandler(ListBox* super, int ch);


#endif
