/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_ColorsPanel
#define HEADER_ColorsPanel


#include "Panel.h"
#include "CheckItem.h"
#include "Settings.h"
#include "ScreenManager.h"

#include "debug.h"
#include <assert.h>


typedef struct ColorsPanel_ {
   Panel super;

   Settings* settings;
   ScreenManager* scr;
   bool check[5];
} ColorsPanel;


ColorsPanel* ColorsPanel_new(Settings* settings, ScreenManager* scr);

void ColorsPanel_delete(Object* object);

HandlerResult ColorsPanel_EventHandler(Panel* super, int ch);


#endif
