/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_ColumnsListBox
#define HEADER_ColumnsListBox


#include "ListBox.h"
#include "Settings.h"
#include "ScreenManager.h"

#include "debug.h"
#include <assert.h>


typedef struct ColumnsListBox_ {
   ListBox super;

   Settings* settings;
   TypedVector* columns;
   ScreenManager* scr;
} ColumnsListBox;


ColumnsListBox* ColumnsListBox_new(Settings* settings, ScreenManager* scr);

void ColumnsListBox_delete(Object* object);

void ColumnsListBox_update(ListBox* super);

HandlerResult ColumnsListBox_eventHandler(ListBox* super, int ch);

#endif
