/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_CPUMeter
#define HEADER_CPUMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include <stdlib.h>
#include <curses.h>
#include <string.h>
#include <math.h>
#include <sys/param.h>

#include "debug.h"
#include <assert.h>


typedef struct CPUMeter_ CPUMeter;

struct CPUMeter_ {
   Meter super;
   ProcessList* pl;
   int processor;
};


CPUMeter* CPUMeter_new(ProcessList* pl, int processor);

void CPUMeter_setValues(Meter* cast);

void CPUMeter_display(Object* cast, RichString* out);

#endif
