/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUMeter
#define HEADER_CPUMeter
/*
htop - CPUMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int CPUMeter_attributes[];

#ifndef MIN
#define MIN(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef MAX
#define MAX(a,b) ((a)>(b)?(a):(b))
#endif

extern MeterClass CPUMeter_class;

extern MeterClass AllCPUsMeter_class;

extern MeterClass AllCPUs2Meter_class;

extern MeterClass LeftCPUsMeter_class;

extern MeterClass RightCPUsMeter_class;

extern MeterClass LeftCPUs2Meter_class;

extern MeterClass RightCPUs2Meter_class;


#endif
