/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUMeter
#define HEADER_CPUMeter
/*
htop - CPUMeter.c
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include <stdlib.h>
#include <curses.h>
#include <string.h>
#include <math.h>

#include "debug.h"
#include <assert.h>




#ifndef MIN
#define MIN(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef MAX
#define MAX(a,b) ((a)>(b)?(a):(b))
#endif

void CPUMeter_init(Meter* this);

void CPUMeter_setValues(Meter* this, char* buffer, int size);

void CPUMeter_display(Object* cast, RichString* out);

void AllCPUsMeter_init(Meter* this);

void AllCPUsMeter_done(Meter* this);

void AllCPUsMeter_setMode(Meter* this, int mode);

void AllCPUsMeter_draw(Meter* this, int x, int y, int w);

#endif
