/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_DisplayOptionsListBox
#define HEADER_DisplayOptionsListBox


#include "ListBox.h"
#include "CheckItem.h"
#include "Settings.h"
#include "ScreenManager.h"

#include "debug.h"
#include <assert.h>


typedef struct DisplayOptionsListBox_ {
   ListBox super;

   Settings* settings;
   ScreenManager* scr;
} DisplayOptionsListBox;


DisplayOptionsListBox* DisplayOptionsListBox_new(Settings* settings, ScreenManager* scr);

void DisplayOptionsListBox_delete(Object* object);

HandlerResult DisplayOptionsListBox_EventHandler(ListBox* super, int ch);


#endif
