/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_EnvScreen
#define HEADER_EnvScreen

#include "ProcessList.h"
#include "Panel.h"
#include "FunctionBar.h"

typedef struct EnvScreen_ {
   Process* process;
   Panel* display;
   FunctionBar* bar;
} EnvScreen;

EnvScreen* EnvScreen_new(Process* process);

void EnvScreen_delete(EnvScreen* this);

void EnvScreen_run(EnvScreen* this);

#endif
