/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_FunctionBar
#define HEADER_FunctionBar
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Object.h"
#include "CRT.h"

#include "debug.h"
#include <assert.h>

#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <curses.h>


typedef struct FunctionBar_ {
   Object super;
   int size;
   char** functions;
   char** keys;
   int* events;
   bool staticData;
} FunctionBar;

extern char* FUNCTIONBAR_CLASS;

FunctionBar* FunctionBar_new(int size, char** functions, char** keys, int* events);

void FunctionBar_delete(Object* this);

void FunctionBar_draw(FunctionBar* this, char* buffer);

void FunctionBar_setLabel(FunctionBar* this, int event, char* text);

void FunctionBar_drawAttr(FunctionBar* this, char* buffer, int attr);

int FunctionBar_synthesizeEvent(FunctionBar* this, int pos);

#endif
