/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_HostnameMeter
#define HEADER_HostnameMeter
/*
htop - HostnameMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int HostnameMeter_attributes[];

extern MeterType HostnameMeter;

#endif
