/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_htop
#define HEADER_htop
/*
htop - htop.h
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "ProcessList.h"
#include "CRT.h"
#include "ListBox.h"
#include "UsersTable.h"
#include "SignalItem.h"
#include "RichString.h"
#include "Settings.h"
#include "ScreenManager.h"
#include "FunctionBar.h"
#include "ListItem.h"
#include "CategoriesListBox.h"
#include "SignalsListBox.h"

#include "config.h"
#include "debug.h"

#include <unistd.h>
#include <math.h>
#include <sys/param.h>
#include <ctype.h>
#include <stdbool.h>

int usleep(int usec);

//#link m

#define INCSEARCH_MAX 40


void printVersionFlag();

void printHelpFlag();

void showHelp();

void showColumnConfig(ProcessList* pl);

void Setup_run(Settings* settings, int headerHeight);

int main(int argc, char** argv);

#endif
