/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_htop
#define HEADER_htop
/*
htop - htop.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

//#link m

#define COPYRIGHT "(C) 2004-2014 Hisham Muhammad"


typedef enum {
   HTOP_OK = 0x00,
   HTOP_REFRESH = 0x01,
   HTOP_RECALCULATE = 0x03, // implies HTOP_REFRESH
   HTOP_SAVE_SETTINGS = 0x04,
   HTOP_KEEP_FOLLOWING = 0x08,
   HTOP_QUIT = 0x10,
   HTOP_REDRAW_BAR = 0x20,
   HTOP_UPDATE_PANELHDR = 0x41, // implies HTOP_REFRESH
} Htop_Reaction;

typedef Htop_Reaction (*Htop_Action)();

typedef struct State_ {
   IncSet* inc;
   Settings* settings;
   UsersTable* ut;
} State;

typedef bool(*ForeachProcessFn)(Process*, size_t);


// ----------------------------------------

void setBindings(Htop_Action* keys);

// ----------------------------------------

int main(int argc, char** argv);

#endif
