/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_LoadAverageMeter
#define HEADER_LoadAverageMeter
/*
htop - LoadAverageMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int LoadAverageMeter_attributes[];

extern int LoadMeter_attributes[];

extern MeterType LoadAverageMeter;

extern MeterType LoadMeter;

#endif
