/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_LoadAverageMeter
#define HEADER_LoadAverageMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include <curses.h>

#include "debug.h"


typedef struct LoadAverageMeter_ LoadAverageMeter;

struct LoadAverageMeter_ {
   Meter super;
   ProcessList* pl;
};



LoadAverageMeter* LoadAverageMeter_new();


void LoadAverageMeter_setValues(Meter* cast);

void LoadAverageMeter_display(Object* cast, RichString* out);

#endif
