/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_MemoryMeter
#define HEADER_MemoryMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include <stdlib.h>
#include <curses.h>
#include <string.h>
#include <math.h>
#include <sys/param.h>

#include "debug.h"
#include <assert.h>


typedef struct MemoryMeter_ MemoryMeter;

struct MemoryMeter_ {
   Meter super;
   ProcessList* pl;
   char* wideFormat;
   int wideLimit;
};


MemoryMeter* MemoryMeter_new(ProcessList* pl);

void MemoryMeter_setValues(Meter* cast);

void MemoryMeter_display(Object* cast, RichString* out);

#endif
