/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_MetersPanel
#define HEADER_MetersPanel


#include "Panel.h"
#include "Settings.h"
#include "ScreenManager.h"

#include "debug.h"
#include <assert.h>


typedef struct MetersPanel_ {
   Panel super;

   Settings* settings;
   Vector* meters;
   ScreenManager* scr;
} MetersPanel;


MetersPanel* MetersPanel_new(Settings* settings, char* header, Vector* meters, ScreenManager* scr);

#endif
