/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_RichString
#define HEADER_RichString


#include <stdlib.h>
#include <string.h>
#include <curses.h>

#include "debug.h"
#include <assert.h>

#define RICHSTRING_MAXLEN 300


#define RichString_init(this) (this)->len = 0
#define RichString_initVal(this) (this).len = 0

typedef struct RichString_ {
   int len;
   chtype chstr[RICHSTRING_MAXLEN+1];
} RichString;


#ifndef MIN
#define MIN(a,b) ((a)<(b)?(a):(b))
#endif

extern void RichString_appendn(RichString* this, int attrs, char* data, int len);

extern void RichString_append(RichString* this, int attrs, char* data);

void RichString_write(RichString* this, int attrs, char* data);

void RichString_setAttr(RichString *this, int attrs);

void RichString_applyAttr(RichString *this, int attrs);

RichString RichString_quickString(int attrs, char* data);

#endif
