/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Settings
#define HEADER_Settings
/*
htop - Settings.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#define DEFAULT_DELAY 15

#include "ProcessList.h"
#include "Header.h"
#include <stdbool.h>

typedef struct Settings_ {
   char* userSettings;
   ProcessList* pl;
   Header* header;
   int colorScheme;
   bool changed;
   int delay;
} Settings;


void Settings_delete(Settings* this);

bool Settings_write(Settings* this);

Settings* Settings_new(ProcessList* pl, Header* header, int cpuCount);

#endif
