/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SignalsPanel
#define HEADER_SignalsPanel

#include "Panel.h"
#include "ListItem.h"
#include "RichString.h"

#include "debug.h"
#include <assert.h>

#include <ctype.h>


typedef struct SignalItem_ {
   const char* name;
   int number;
} SignalItem;

typedef struct SignalsPanel_ {
   Panel super;
} SignalsPanel;


SignalsPanel* SignalsPanel_new(int x, int y, int w, int h);

void SignalsPanel_reset(SignalsPanel* this);

#endif
