/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SignalItem
#define HEADER_SignalItem
/*
htop - SignalItem.h
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "String.h"
#include "Object.h"
#include "RichString.h"
#include <string.h>

#include "debug.h"

#define SIGNAL_COUNT 34


typedef struct Signal_ {
   Object super;
   char* name;
   int number;
} Signal;


#ifdef DEBUG
extern char* SIGNAL_CLASS;
#else
#define SIGNAL_CLASS NULL
#endif

Signal* Signal_new(char* name, int number);

void Signal_delete(Object* cast);

void Signal_display(Object* cast, RichString* out);

int Signal_getSignalCount();

Signal** Signal_getSignalTable();

#endif
