/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SignalsPanel
#define HEADER_SignalsPanel

#include "Panel.h"
#include "ListItem.h"
#include "RichString.h"

#include "debug.h"
#include <assert.h>

#include <ctype.h>


typedef struct SignalsPanel_ {
   Panel super;
   ListItem** signals;
} SignalsPanel;


#ifndef SIGNAL_COUNT
#define SIGNAL_COUNT 34
#endif

SignalsPanel* SignalsPanel_new(int x, int y, int w, int h);

void SignalsPanel_reset(SignalsPanel* this);

#endif
