/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_SignalsListBox
#define HEADER_SignalsListBox

#include "ListBox.h"
#include "SignalItem.h"
#include "RichString.h"

#include "debug.h"
#include <assert.h>

#include <ctype.h>


typedef struct SignalsListBox_ {
   ListBox super;

   int state;
   Signal** signals;
} SignalsListBox;


SignalsListBox* SignalsListBox_new(int x, int y, int w, int h);

void SignalsListBox_delete(Object* object);

void SignalsListBox_reset(SignalsListBox* this);

HandlerResult SignalsListBox_EventHandler(ListBox* super, int ch);

#endif
