/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_String
#define HEADER_String
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#define _GNU_SOURCE
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdio.h>

#include "debug.h"

#define String_startsWith(s, match) (strstr((s), (match)) == (s))

extern char* String_copy(char* orig);

char* String_cat(char* s1, char* s2);

char* String_trim(char* in);

extern int String_eq(const char* s1, const char* s2);

char** String_split(char* s, char sep);

void String_freeArray(char** s);

int String_contains_i(char* s, char* match);

char* String_getToken(const char* line, const unsigned short int numMatch);

#endif
