/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SwapMeter
#define HEADER_SwapMeter
/*
htop
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include <stdlib.h>
#include <curses.h>
#include <string.h>
#include <math.h>
#include <sys/param.h>

#include "debug.h"
#include <assert.h>

extern int SwapMeter_attributes[];

extern MeterType SwapMeter;

#endif
