/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SwapMeter
#define HEADER_SwapMeter
/*
htop - SwapMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#define KILOBYTE 1
#define MEGABYTE 1024
#define GIGABYTE 1048576

extern int SwapMeter_attributes[];

/* NOTE: Value is in kilobytes */
extern MeterType SwapMeter;

#endif
