/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_TasksMeter
#define HEADER_TasksMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include "CRT.h"

#include "debug.h"


typedef struct TasksMeter_ TasksMeter;

struct TasksMeter_ {
   Meter super;
   ProcessList* pl;
};


TasksMeter* TasksMeter_new(ProcessList* pl);

void TasksMeter_setValues(Meter* cast);

void TasksMeter_display(Object* cast, RichString* out);

#endif
