/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_TraceScreen
#define HEADER_TraceScreen
/*
htop - TraceScreen.h
(C) 2005-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Process.h"
#include "Panel.h"
#include "FunctionBar.h"

typedef struct TraceScreen_ {
   Process* process;
   Panel* display;
   FunctionBar* bar;
   bool tracing;
} TraceScreen;


TraceScreen* TraceScreen_new(Process* process);

void TraceScreen_delete(TraceScreen* this);

void TraceScreen_run(TraceScreen* this);

#endif
