/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_UptimeMeter
#define HEADER_UptimeMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include "CRT.h"

#include "debug.h"



void UptimeMeter_setValues(Meter* cast, char* buffer, int len);

#endif
