/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_UptimeMeter
#define HEADER_UptimeMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include "ProcessList.h"

#include "CRT.h"

#include "debug.h"


typedef struct UptimeMeter_ UptimeMeter;

struct UptimeMeter_ {
   Meter super;
   ProcessList* pl;
   int seconds;
   int minutes;
   int hours;
   int days;
};


UptimeMeter* UptimeMeter_new();

void UptimeMeter_setValues(Meter* cast);

void UptimeMeter_display(Object* cast, RichString* out);

#endif
