/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_UsersTable
#define HEADER_UsersTable
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Hashtable.h"
#include "String.h"

#include <stdio.h>
#include <strings.h>
#include <pwd.h>
#include <sys/types.h>

#include "debug.h"
#include <assert.h>

#ifndef SYSCONFDIR
#define SYSCONFDIR "/etc"
#endif

typedef struct UsersTable_ {
   Hashtable* users;
} UsersTable;

UsersTable* UsersTable_new();

void UsersTable_delete(UsersTable* this);

char* UsersTable_getRef(UsersTable* this, int uid);

inline int UsersTable_size(UsersTable* this);

void UsersTable_foreach(UsersTable*, Hashtable_PairFunction, void*);

#endif
