/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_DarwinProcess
#define HEADER_DarwinProcess
/*
htop - DarwinProcess.h
(C) 2015 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Settings.h"

#define Process_delete DarwinProcess_delete


Process* DarwinProcess_new(Settings* settings);

void DarwinProcess_delete(Object* cast);


#endif
