/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FreeBSDProcessList
#define HEADER_FreeBSDProcessList
/*
htop - FreeBSDProcessList.h
(C) 2014 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/


#include <kvm.h>

typedef struct FreeBSDProcessList_ {
   ProcessList super;
   kvm_t* kd;
} FreeBSDProcessList;



ProcessList* ProcessList_new(UsersTable* usersTable, Hashtable* pidWhiteList);

void ProcessList_scan(ProcessList* this);

#endif
