/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_openzfs
#define HEADER_openzfs
/*
htop - zfs/openzfs_sysctl.h
(C) 2014 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "zfs/ZfsArcStats.h"

int openzfs_sysctl_init();

void openzfs_sysctl_updateArcStats(ZfsArcStats *stats);

#endif
