/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Battery
#define HEADER_Battery
/*
htop - linux/Battery.h
(C) 2004-2014 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.

Linux battery readings written by Ian P. Hands (iphands@gmail.com, ihands@redhat.com).
*/

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

ACPresence Battery_isOnAC();

double Battery_getProcBatData();

double Battery_getSysBatData();

#endif
