/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_PressureStallMeter
#define HEADER_PressureStallMeter
/*
htop - PressureStallMeter.h
(C) 2004-2011 Hisham H. Muhammad
(C) 2019 Ran Benita
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern MeterClass PressureStallCPUSomeMeter_class;

extern MeterClass PressureStallIOSomeMeter_class;

extern MeterClass PressureStallIOFullMeter_class;

extern MeterClass PressureStallMemorySomeMeter_class;

extern MeterClass PressureStallMemoryFullMeter_class;

#endif
